export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const SIGN_UP_VERIFY_REQUEST = "SIGN_UP_VERIFY_REQUEST";
export const SIGN_UP_VERIFY_SUCCESS = "SIGN_UP_VERIFY_SUCCESS";
export const SIGN_UP_VERIFY_FAILED = "SIGN_UP_VERIFY_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOG_OUT = "LOG_OUT";

export const SEND_EMAIL_CODE_SUCCESS = "SEND_EMAIL_CODE_SUCCESS";

export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_BIRTHDATE = "CHANGE_BIRTHDATE";
export const CHANGE_ADDRESS = "CHANGE_ADDRESS";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_PICTURE = "CHANGE_PICTURE";
export const GET_USER_ID = "GET_USER_ID";

export const ADD_POST = "ADD_POST";
export const ADD_POST_FAILED = "ADD_POST_FAILED";
export const AFTER_POST_SUCCESS = "AFTER_POST_SUCCESS";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILED = "DELETE_POST_FAILED";

export const GET_USER_POST_FAILED = "GET_USER_POST_FAILED";
export const GET_USER_POST_SUCCESS = "GET_USER_POST_SUCCESS";
